#!groovy

@Library('jenkins-sharelibrary') _

def mytools = new org.devops.tools()

hello()

pipeline{
    //指定运行此流水线的节点
    agent { node { label "jenkins-salve01"}}

    tools {
        maven 'maven-3.6.3'
    }
//   parameters { string(name: 'DEPLOY_ENV', defaultValue: 'staging', description: '')}

    options {
        timeout(time: 1, unit: 'HOURS')
    }
    //流水线的阶段
    stages{
        //阶段1 获取代码
        stage("GetCode"){
            when { environment name: 'test', value: 'abcd' }
            steps{
                script{
                    println("获取代码")
                    println("${test}")
                    mytools.PrintMes("获取代码",'green')
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
        }
        //阶段2 检查代码
        stage("CheckOut"){
            steps{
                script{
                    println("检查代码")
                    mytools.PrintMes("检查代码",'green')
                }
            }
        }
        //阶段3 打包代码
        stage("Build"){
            steps{
                script{
                    println("打包代码")
                    mytools.PrintMes("打包代码",'green')
                    mvnHome = tool "maven-3.6.3"
                    println(mvnHome)
                    sh "${mvnHome}/bin/mvn -version"
                }
            }
        }
    }

    post {
        always{
            script{
                println("流水线结束后，经常做的事情")
            }
        }

        success{
            script{
                println("流水线成功后，要做的事情")
            }

        }
        failure{
            script{
                println("流水线失败后，要做的事情")
            }
        }

        aborted{
            script{
                println("流水线取消后，要做的事情")
            }

        }
    }
}